# Generated by Django 5.0.6 on 2024-05-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
